//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovaSchool.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using InnovaSchool.Models;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class innovaEntities : DbContext
    {
        public innovaEntities()
            : base("name=innovaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GD_Area> GD_Area { get; set; }
        public virtual DbSet<GD_Articulo> GD_Articulo { get; set; }
        public virtual DbSet<GD_Documento> GD_Documento { get; set; }
        public virtual DbSet<GD_Empleado> GD_Empleado { get; set; }
        public virtual DbSet<GD_Estado> GD_Estado { get; set; }
        public virtual DbSet<GD_Proveedor> GD_Proveedor { get; set; }
        public virtual DbSet<GD_ProveedorArticulo> GD_ProveedorArticulo { get; set; }
        public virtual DbSet<GD_SolAdquisicion> GD_SolAdquisicion { get; set; }
        public virtual DbSet<GD_SolAdquisicionDet> GD_SolAdquisicionDet { get; set; }
        public virtual DbSet<GD_UnidadMedida> GD_UnidadMedida { get; set; }
        public virtual DbSet<GD_SolCotizacion> GD_SolCotizacion { get; set; }
        public virtual DbSet<GD_SolCotizacionDet> GD_SolCotizacionDet { get; set; }
    
        public virtual int sp_ActualizarCotizacion(Nullable<int> codSolCotizacion)
        {
            var codSolCotizacionParameter = codSolCotizacion.HasValue ?
                new ObjectParameter("CodSolCotizacion", codSolCotizacion) :
                new ObjectParameter("CodSolCotizacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ActualizarCotizacion", codSolCotizacionParameter);
        }
    
        public virtual ObjectResult<sp_BuscarArticulos_SolAdquisicion_Result> sp_BuscarArticulos_SolAdquisicion(Nullable<int> codSolAdquisicion)
        {
            var codSolAdquisicionParameter = codSolAdquisicion.HasValue ?
                new ObjectParameter("CodSolAdquisicion", codSolAdquisicion) :
                new ObjectParameter("CodSolAdquisicion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BuscarArticulos_SolAdquisicion_Result>("sp_BuscarArticulos_SolAdquisicion", codSolAdquisicionParameter);
        }
    
        public virtual ObjectResult<sp_ConsultarCotizacion_Result> sp_ConsultarCotizacion(Nullable<int> codSolCotizacion)
        {
            var codSolCotizacionParameter = codSolCotizacion.HasValue ?
                new ObjectParameter("CodSolCotizacion", codSolCotizacion) :
                new ObjectParameter("CodSolCotizacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsultarCotizacion_Result>("sp_ConsultarCotizacion", codSolCotizacionParameter);
        }
    
        public virtual ObjectResult<string> sp_EliminarArticuloSolCotizacion(Nullable<int> codSolCotizacion, Nullable<int> codArticulo)
        {
            var codSolCotizacionParameter = codSolCotizacion.HasValue ?
                new ObjectParameter("CodSolCotizacion", codSolCotizacion) :
                new ObjectParameter("CodSolCotizacion", typeof(int));
    
            var codArticuloParameter = codArticulo.HasValue ?
                new ObjectParameter("CodArticulo", codArticulo) :
                new ObjectParameter("CodArticulo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_EliminarArticuloSolCotizacion", codSolCotizacionParameter, codArticuloParameter);
        }
    
        public virtual int sp_EliminarCotizacion(Nullable<int> codSolCotizacion)
        {
            var codSolCotizacionParameter = codSolCotizacion.HasValue ?
                new ObjectParameter("CodSolCotizacion", codSolCotizacion) :
                new ObjectParameter("CodSolCotizacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminarCotizacion", codSolCotizacionParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_GrabarCabSolCotizacion(Nullable<int> codSolAdquisicion, Nullable<int> codProveedor)
        {
            var codSolAdquisicionParameter = codSolAdquisicion.HasValue ?
                new ObjectParameter("CodSolAdquisicion", codSolAdquisicion) :
                new ObjectParameter("CodSolAdquisicion", typeof(int));
    
            var codProveedorParameter = codProveedor.HasValue ?
                new ObjectParameter("CodProveedor", codProveedor) :
                new ObjectParameter("CodProveedor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_GrabarCabSolCotizacion", codSolAdquisicionParameter, codProveedorParameter);
        }
    
        public virtual ObjectResult<string> sp_GrabarDetSolCotizacion(Nullable<int> codSolCotizacion, Nullable<int> codSolAdquisicion, Nullable<int> codProveedor)
        {
            var codSolCotizacionParameter = codSolCotizacion.HasValue ?
                new ObjectParameter("CodSolCotizacion", codSolCotizacion) :
                new ObjectParameter("CodSolCotizacion", typeof(int));
    
            var codSolAdquisicionParameter = codSolAdquisicion.HasValue ?
                new ObjectParameter("CodSolAdquisicion", codSolAdquisicion) :
                new ObjectParameter("CodSolAdquisicion", typeof(int));
    
            var codProveedorParameter = codProveedor.HasValue ?
                new ObjectParameter("CodProveedor", codProveedor) :
                new ObjectParameter("CodProveedor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_GrabarDetSolCotizacion", codSolCotizacionParameter, codSolAdquisicionParameter, codProveedorParameter);
        }
    
        public virtual ObjectResult<sp_ListaCotizaciones_Result> sp_ListaCotizaciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ListaCotizaciones_Result>("sp_ListaCotizaciones");
        }
    
        public virtual ObjectResult<string> sp_ObetenerEstadoCotizacion(Nullable<int> codSolCotizacion)
        {
            var codSolCotizacionParameter = codSolCotizacion.HasValue ?
                new ObjectParameter("CodSolCotizacion", codSolCotizacion) :
                new ObjectParameter("CodSolCotizacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_ObetenerEstadoCotizacion", codSolCotizacionParameter);
        }
    }
}
