//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovaSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GD_Articulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GD_Articulo()
        {
            this.GD_ProveedorArticulo = new HashSet<GD_ProveedorArticulo>();
            this.GD_SolCotizacionDet = new HashSet<GD_SolCotizacionDet>();
        }
    
        public int CodArticulo { get; set; }
        public string DescArticulo { get; set; }
        public string CodUniMedida { get; set; }
        public string Modelo { get; set; }
        public string Marca { get; set; }
        public string Observacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GD_ProveedorArticulo> GD_ProveedorArticulo { get; set; }
        public virtual GD_UnidadMedida GD_UnidadMedida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GD_SolCotizacionDet> GD_SolCotizacionDet { get; set; }
    }
}
