//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovaSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GD_SolAdquisicion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GD_SolAdquisicion()
        {
            this.GD_SolAdquisicionDet = new HashSet<GD_SolAdquisicionDet>();
            this.GD_SolCotizacion = new HashSet<GD_SolCotizacion>();
        }
    
        public int CodSolAdquisicion { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public string CodEstado { get; set; }
        public int CodEmpleado { get; set; }
        public int CodSolicitante { get; set; }
        public string Observacion { get; set; }
        public string NroInforme { get; set; }
    
        public virtual GD_Empleado GD_Empleado { get; set; }
        public virtual GD_Empleado GD_Empleado1 { get; set; }
        public virtual GD_Estado GD_Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GD_SolAdquisicionDet> GD_SolAdquisicionDet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GD_SolCotizacion> GD_SolCotizacion { get; set; }
    }
}
