//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovaSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GD_SolCotizacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GD_SolCotizacion()
        {
            this.GD_SolCotizacionDet = new HashSet<GD_SolCotizacionDet>();
        }
    
        public int CodSolCotizacion { get; set; }
        public Nullable<System.DateTime> FechaCotizacion { get; set; }
        public Nullable<int> CodSolAdquisicion { get; set; }
        public Nullable<int> CodProveedor { get; set; }
        public string CodEstado { get; set; }
    
        public virtual GD_SolAdquisicion GD_SolAdquisicion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GD_SolCotizacionDet> GD_SolCotizacionDet { get; set; }
    }
}
