//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovaSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GD_SolCotizacionDet
    {
        public int CodSolCotizacion { get; set; }
        public int CodArticulo { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual GD_Articulo GD_Articulo { get; set; }
        public virtual GD_SolCotizacion GD_SolCotizacion { get; set; }
    }
}
