//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InnovaSchool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GD_SolAdquisicionDet
    {
        public int CodSolAdquisicionDet { get; set; }
        public int CodSolAdquisicion { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public int CodProveedor { get; set; }
        public int CodArticulo { get; set; }
    
        public virtual GD_ProveedorArticulo GD_ProveedorArticulo { get; set; }
        public virtual GD_SolAdquisicion GD_SolAdquisicion { get; set; }
    }
}
